services:
  # ---------------- SOCK SHOP ----------------
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    ports:
      - "8079:8079"
    depends_on:
      - catalogue
      - otel

  catalogue:
    image: weaveworksdemos/catalogue:0.3.5

  carts:
    image: weaveworksdemos/carts:0.4.8

  user:
    image: weaveworksdemos/user:0.4.7

  orders:
    image: weaveworksdemos/orders:0.4.7

  payment:
    image: weaveworksdemos/payment:0.4.3

  shipping:
    image: weaveworksdemos/shipping:0.4.8

  rabbitmq:
    image: rabbitmq:3-management

  queue-master:
    image: weaveworksdemos/queue-master:0.3.1
    depends_on:
      - rabbitmq

  # ---------------- LOCUST ----------------
  locust:
    build: ./locust
    ports:
      - "8089:8089"
    depends_on:
      - front-end
      - otel
      - log-stream
    environment:
      - LOG_STREAM_URL=http://log-stream:8080/v1/logs

  log-stream:
    build: ./log-stream
    ports:
      - "8090:8080"

  drain3:
    build: ./drain3
    depends_on:
      - log-stream
      - otel
      - dashboard
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - LOG_STREAM_URL=http://log-stream:8080/v1/stream
      - TEMPO_URL=http://otel:3200
      - LOKI_URL=http://otel:3100
      - PROM_URL=http://otel:9090
      - SLM_URL=http://host.docker.internal:11434/api/generate
      - SLM_MODEL=llama3.2
      # Log LSTM (unchanged)
      - DRAIN3_WINDOW=24
      - DRAIN3_FEAT_DIM=8
      - DRAIN3_WARMUP=64
      - DRAIN3_Z=4.5
      - DRAIN3_FORCE_RULES=1
      # - DRAIN3_CHECKPOINT=/checkpoints/lstm_best.pt
      # Metric LSTM
      - PROM_SCRAPE_INTERVAL=15
      - DRAIN3_METRIC_WINDOW=24
      - DRAIN3_METRIC_WARMUP=32
      - DRAIN3_METRIC_Z=4.0
      - DRAIN3_METRIC_CHECKPOINT=/checkpoints/lstm_metric_best.pt
      - DASHBOARD_URL=http://dashboard:8050
    volumes:
      - ./offline_lstm/checkpoints:/checkpoints:ro

  # ---------------- DASHBOARD ----------------
  dashboard:
    build: ./dashboard
    ports:
      - "8050:8050"   # Anomaly Dashboard UI
    depends_on:
      - otel
      - log-stream
    environment:
      - PROM_URL=http://otel:9090
      - LOG_STREAM_URL=http://log-stream:8080

  # ---------------- LGTM STACK ----------------
  otel:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000"   # Grafana UI
      - "3100:3100"   # Loki
      - "3200:3200"   # Tempo query
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "9090:9090"   # Prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin